# Generated by Django 6.0.6 on 2026-07-08 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_permissions', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('confidential_content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_private_document', 'Can view specific secure document'), ('edit_securedocument', 'Can edit specific secure document')),
            },
        ),
    ]
