# Generated by Django 6.0.6 on 2026-07-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_permissions', '0004_securedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securedocument',
            options={'permissions': (('edit_securedocument', 'Can edit specific secure document'),)},
        ),
    ]
