# Generated by Django 6.0.6 on 2026-07-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_permissions', '0005_alter_securedocument_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securedocument',
            old_name='owner',
            new_name='user',
        ),
    ]
