# Generated by Django 6.0.6 on 2026-07-08 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_permissions', '0007_alter_securedocument_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
