from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import get_object_or_404
from rest_framework.exceptions import ValidationError, PermissionDenied
from rest_framework.permissions import IsAuthenticated
from django.db import transaction as db_transaction
from django.db.models import Sum

from .models import Account, Transaction
from .permissions import IsAccountOwner
from .serializers import (
    AccountListSerializer,
    AccountDetailSerializer,
    TransactionDetailSerializer,
    TransactionListSerializer,
    StatementSerializer,
)
from datetime import datetime
def _parse_date(value, param_name):
    try:
        datetime.strptime(value, "%Y-%m-%d")
        return value
    except ValueError:

        raise ValidationError({param_name: "Use YYYY-MM-DD format."})
 
class AccountViewSet(ModelViewSet):
    """
    CRUD for Account model.
 
    Endpoints (auto-generated by DefaultRouter):
      GET    /accounts/                → list
      POST   /accounts/                → create
      GET    /accounts/{id}/           → retrieve
      PUT    /accounts/{id}/           → update (full)
      PATCH  /accounts/{id}/           → partial_update
      DELETE /accounts/{id}/           → destroy
 
    Custom actions:
      POST   /accounts/{id}/freeze/    → Task 3: freeze account
      GET    /accounts/{id}/statement/ → Task 3: account statement
    """
    permission_classes = [IsAuthenticated, IsAccountOwner]
 

    def get_queryset(self):
        """
        Override: only return accounts owned by the requesting user.
        Prevents horizontal privilege escalation.
        """
        qs = Account.objects.filter(owner=self.request.user)
        account_type = self.request.query_params.get("type")
        status_filter = self.request.query_params.get("status")
        if account_type:
            qs = qs.filter(account_type=account_type)
        if status_filter:
            qs = qs.filter(status=status_filter)
        return qs
 
    def get_serializer_class(self):
        """
        Override: return a lightweight serializer for list action,
        full serializer for all other actions.
        """
        if self.action == "list":
            return AccountListSerializer
        return AccountDetailSerializer
 
    def perform_create(self, serializer):

        serializer.save(owner=self.request.user)
 

    @action(detail=True, methods=["post"], url_path="freeze")
    def freeze(self, request, pk=None):
        """
        POST /accounts/{id}/freeze/
 
        Freezes an active account. Frozen accounts cannot have
        new transactions created against them.
        """
        account = self.get_object()  
 
        if account.status != "active":
            return Response(
                {"detail": f"Cannot freeze an account with status '{account.status}'."},
                status=status.HTTP_400_BAD_REQUEST,
            )
 
        account.status = "frozen"
        account.save(update_fields=["status", "updated_at"])
        return Response(
            {"detail": "Account frozen.", "status": account.status},
            status=status.HTTP_200_OK,
        )
 
    @action(detail=True, methods=["post"], url_path="unfreeze")
    def unfreeze(self, request, pk=None):
        """
        POST /accounts/{id}/unfreeze/
        Reactivates a frozen account.
        """
        account = self.get_object()
        if account.status != "frozen":
            return Response(
                {"detail": f"Account is not frozen (current status: '{account.status}')."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        account.status = "active"
        account.save(update_fields=["status", "updated_at"])
        return Response(
            {"detail": "Account reactivated.", "status": account.status},
            status=status.HTTP_200_OK,
        )
 

    @action(detail=True, methods=["get"], url_path="statement")
    def statement(self, request, pk=None):
        """
        GET /accounts/{id}/statement/
 
        Returns a paginated transaction statement with summary stats.
        """


        account = self.get_object()
        transactions = account.transactions.all()
 
        from_date = request.query_params.get("from")
        to_date = request.query_params.get("to")
        
        if from_date:
            from_date = _parse_date(from_date, "from")
            transactions = transactions.filter(created_at__date__gte=from_date)
        if to_date:
            to_date = _parse_date(to_date, "to")
            transactions = transactions.filter(created_at__date__lte=to_date)
 
        summary = {
            "total_deposits": transactions.filter(transaction_type="deposit")
                .aggregate(total=Sum("amount"))["total"] or 0,
            "total_withdrawals": transactions.filter(transaction_type="withdrawal")
                .aggregate(total=Sum("amount"))["total"] or 0,
            "transaction_count": transactions.count(),
        }
 
        return Response({
            "account": AccountDetailSerializer(account, context=self.get_serializer_context()).data,
            "period": {"from": from_date or "all time", "to": to_date or "present"},
            "summary": summary,
            "transactions": StatementSerializer(transactions, many=True).data,
        }, status=status.HTTP_200_OK)
 
 
class TransactionViewSet(ModelViewSet):
    """
    CRUD for Transaction model.
 
    Endpoints (auto-generated by DefaultRouter):
      GET    /transactions/            → list user's transactions
      POST   /transactions/            → create (deposit/withdrawal/transfer)
      GET    /transactions/{id}/       → retrieve
      PUT    /transactions/{id}/       → update (only description editable)
      PATCH  /transactions/{id}/       → partial_update
      DELETE /transactions/{id}/       → destroy (soft-delete recommended)
 
    Custom action:
      POST   /transactions/{id}/reverse/ → Task 3: reverse a transaction
    """
    permission_classes = [IsAuthenticated, IsAccountOwner]
    http_method_names = ["get", "post", "patch", "delete", "head", "options"]
 
    def get_queryset(self):
        """
        Return transactions for accounts owned by the requesting user.
        Optionally filter by account, type, or status.
        """
        qs = Transaction.objects.filter(account__owner=self.request.user)
 
        account_id = self.request.query_params.get("account")
        tx_type = self.request.query_params.get("type")
        tx_status = self.request.query_params.get("status")
 
        if account_id:
            qs = qs.filter(account_id=account_id)
        if tx_type:
            qs = qs.filter(transaction_type=tx_type)
        if tx_status:
            qs = qs.filter(status=tx_status)
        return qs
 

    def get_serializer_class(self):
        if self.action == "list":
            return TransactionListSerializer
        return TransactionDetailSerializer
 

    def perform_create(self, serializer):
        with db_transaction.atomic():
            account = Account.objects.select_for_update().get(
                pk=serializer.validated_data["account"].pk
            )

            if account.owner != self.request.user:
                raise PermissionDenied("You do not own this account.")

            if account.status != "active":
                raise ValidationError(
                    {"account": f"Account is {account.status} and cannot accept transactions."}
                )

            amount = serializer.validated_data["amount"]
            tx_type = serializer.validated_data["transaction_type"]
            balance_before = account.balance

            if tx_type == "deposit":
                account.balance += amount

            elif tx_type == "withdrawal":
                if account.balance < amount:
                    raise ValidationError(
                        {"amount": "Insufficient balance."}
                    )
                account.balance -= amount

            elif tx_type == "transfer":
                if account.balance < amount:
                    raise ValidationError(
                        {"amount": "Insufficient balance for transfer."}
                    )
                account.balance -= amount

            account.save(update_fields=["balance", "updated_at"])

            serializer.save(
                balance_before=balance_before,
                balance_after=account.balance,
                status="completed",
            )


    @action(detail=True, methods=["post"], url_path="reverse")
    def reverse(self, request, pk=None):
        """
        POST /transactions/{id}/reverse/
 
        Reverses a completed transaction by creating an equal and
        opposite transaction, then marking the original as 'reversed'.
        """
        with db_transaction.atomic():
            original = get_object_or_404(Transaction.objects.select_for_update(),pk=pk)
            account  = Account.objects.select_for_update().get(pk=original.account_id)
    
            if original.status == "reversed":
                return Response(
                    {"detail": "This transaction has already been reversed."},
                    status=status.HTTP_400_BAD_REQUEST,
                )
            if original.status != "completed":
                return Response(
                    {"detail": f"Only completed transactions can be reversed (current: {original.status})."},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            reversal_type_map = {
                "deposit": "withdrawal",
                "withdrawal": "deposit",
                "transfer": "deposit",  
            }
            reversal_type = reversal_type_map[original.transaction_type]
    
            # Apply reversal to balance
            balance_before = account.balance
            if reversal_type == "deposit":
                account.balance += original.amount
            else: 
                if account.balance < original.amount:
                    return Response(
                        {"detail": "Insufficient balance to reverse this transaction."},
                        status=status.HTTP_400_BAD_REQUEST,
                    )
                account.balance -= original.amount
            account.save(update_fields=["balance", "updated_at"])
    
            # Create reversal transaction
            reason = request.data.get("reason", "Manual reversal")
            reversal = Transaction.objects.create(
                account=account,
                transaction_type=reversal_type,
                amount=original.amount,
                balance_before=balance_before,
                balance_after=account.balance,
                description=f"Reversal of {original.reference}. Reason: {reason}",
                status="completed",
            )
    
            # Mark original as reversed
            original.status = "reversed"
            original.reversed_by = reversal
            original.save(update_fields=["status", "reversed_by"])
    
            serializer_ctx = self.get_serializer_context()
            return Response({
                "detail": "Transaction reversed.",
                "original": TransactionDetailSerializer(original, context=serializer_ctx).data,
                "reversal": TransactionDetailSerializer(reversal, context=serializer_ctx).data,
            }, status=status.HTTP_200_OK)
 